USE [master]
GO

/****** Object:  Database [UltimateTeam]    Script Date: 5/10/2025 2:29:14 PM ******/
CREATE DATABASE [UltimateTeam]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'UltimateTeam', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\UltimateTeam.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'UltimateTeam_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\UltimateTeam_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UltimateTeam].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [UltimateTeam] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [UltimateTeam] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [UltimateTeam] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [UltimateTeam] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [UltimateTeam] SET ARITHABORT OFF 
GO

ALTER DATABASE [UltimateTeam] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [UltimateTeam] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [UltimateTeam] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [UltimateTeam] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [UltimateTeam] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [UltimateTeam] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [UltimateTeam] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [UltimateTeam] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [UltimateTeam] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [UltimateTeam] SET  DISABLE_BROKER 
GO

ALTER DATABASE [UltimateTeam] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [UltimateTeam] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [UltimateTeam] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [UltimateTeam] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [UltimateTeam] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [UltimateTeam] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [UltimateTeam] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [UltimateTeam] SET RECOVERY FULL 
GO

ALTER DATABASE [UltimateTeam] SET  MULTI_USER 
GO

ALTER DATABASE [UltimateTeam] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [UltimateTeam] SET DB_CHAINING OFF 
GO

ALTER DATABASE [UltimateTeam] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [UltimateTeam] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [UltimateTeam] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [UltimateTeam] SET QUERY_STORE = OFF
GO

ALTER DATABASE [UltimateTeam] SET  READ_WRITE 
GO


